name: Save News

on:
  workflow_dispatch:
    inputs:
      news_content:
        description: 'Content of the news'
        required: true
        default: ''
      image_url:
        description: 'URL of the image'
        required: false
        default: ''

jobs:
  save_news_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update news.txt
        run: |
          echo "${{ github.event.inputs.news_content }}" > news.txt
          echo "\n[IMAGE_URL]\n" >> news.txt
          echo "${{ github.event.inputs.image_url }}" >> news.txt

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add news.txt
          git commit -m "Update news.txt via GitHub Action"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
